services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    environment:
      - VITE_API_PROXY_TARGET=http://backend:5000

    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: backend

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/main360

    volumes:
      - ./server:/app
      - /app/node_modules

  postgres:
    image: postgres:17

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main360

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
