services:
  db:
    image: postgres:18.3

    container_name: zameen360-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: zameen360

    ports:
      - "5432:5432"

    volumes:
      - zameen360_pgdata:/var/lib/postgresql

volumes:
  zameen360_pgdata: