

export interface CityData {
  name: string;
  localities: string[];
}

export const PAKISTAN_LOCATIONS: CityData[] = [
  {
    name: "Lahore",
    localities: [
      // DHA Phases
      "DHA Phase 1", "DHA Phase 2", "DHA Phase 3", "DHA Phase 4",
      "DHA Phase 5", "DHA Phase 6", "DHA Phase 7", "DHA Phase 8",
      "DHA Phase 9 Town", "DHA Phase 9 Prism", "DHA Phase 10",
      "DHA Phase 11 (Rahbar)", "DHA Phase 12 (EME)", "DHA Phase 13 (Air Avenue)",
      "DHA Lahore Commercial", "Defence Raya",
      // Bahria Town
      "Bahria Town Lahore", "Bahria Town Sector A", "Bahria Town Sector B",
      "Bahria Town Sector C", "Bahria Town Sector D", "Bahria Town Sector E",
      "Bahria Town Sector F", "Bahria Town Jasmine Block", "Bahria Town Tulip Block",
      "Bahria Town Overseas Block", "Bahria Town Tauheed Block",
      "Bahria Orchard Phase 1", "Bahria Orchard Phase 2", "Bahria Orchard Phase 4",
      "Bahria Nasheman", "Bahria Education City", "Bahria EME",
      // Gulberg
      "Gulberg", "Gulberg I", "Gulberg II", "Gulberg III", "Gulberg IV", "Gulberg V",
      "Main Boulevard Gulberg", "M.M. Alam Road", "Liberty Market",
      // Model Town
      "Model Town", "Model Town Extension", "Model Town Block A",
      "Model Town Block B", "Model Town Block C", "Model Town Block D",
      "Model Town Block E", "Model Town Block F", "Model Town Block G",
      "Model Town Link Road",
      // Johar Town
      "Johar Town", "Johar Town Phase 1", "Johar Town Phase 2",
      "Johar Town Block A", "Johar Town Block B", "Johar Town Block C",
      "Johar Town Block D", "Johar Town Block E", "Johar Town Block F",
      "Johar Town Block G", "Johar Town Block H", "Johar Town Block J",
      "Johar Town Block R",
      // Other Housing Societies
      "Wapda Town", "Wapda Town Phase 1", "Wapda Town Phase 2",
      "PCSIR Housing Society", "PCSIR Phase 1", "PCSIR Phase 2",
      "Valencia Housing Society", "Valencia Town",
      "Garden Town", "Garden Town Block A", "Garden Town Block B",
      "Faisal Town", "Faisal Town Block A", "Faisal Town Block B",
      "Iqbal Town", "Iqbal Town Ravi Block", "Iqbal Town Nishtar Block",
      "Iqbal Town Karim Block", "Iqbal Town Mehran Block",
      "Allama Iqbal Town", "Mustafa Town",
      "EME Society", "EME Society Block A", "EME Society Block D",
      "Punjab Coop Housing Society", "Punjab Govt Employees Society",
      "State Life Housing Society", "State Life Phase 1", "State Life Phase 2",
      "Sui Gas Housing Society", "Sui Gas Phase 1", "Sui Gas Phase 2",
      "LDA Avenue Phase 1", "LDA Avenue Phase 2",
      "Lake City", "Lake City Sector M-1", "Lake City Sector M-7",
      "Paragon City", "Paragon City Imperial Block",
      "Izmir Town", "Izmir Town Extension",
      "Al-Kabir Town Phase 1", "Al-Kabir Town Phase 2", "Al-Kabir Town Phase 3",
      "Etihad Town Phase 1", "Etihad Town Phase 2",
      "Architects Engineers Housing Society",
      "NFC Housing Society", "NFC Phase 1", "NFC Phase 2",
      "Khayaban-e-Amin", "Khayaban-e-Amin Phase 1",
      "Canal Garden", "Canal View Housing Scheme",
      "Lahore Smart City", "Capital Smart City Lahore",
      "Jubilee Town", "Sabzazar", "Sabzazar Block A", "Sabzazar Block N",
      "Lahore Motorway City", "Green City Lahore",
      "Eden Builders Housing", "Eden Palace Villas",
      // Askari
      "Askari 10", "Askari 11", "Askari 9 Bedian Road",
      // Cantt & Old City
      "Cantt", "Lahore Cantt", "Mall Road", "The Mall", "Upper Mall",
      "Cavalry Ground", "Cavalry Ground Extension",
      "Sarwar Colony", "Sarwar Road",
      "Shadman", "Shadman I", "Shadman II",
      "Ichra", "Anarkali", "Data Darbar",
      "Mughalpura", "Shalimar", "Baghbanpura",
      "Township", "Township Sector A", "Township Sector B", "Township Sector C",
      "Shadbagh", "Shahdara", "Badami Bagh",
      "Shah Jamal", "Nishtar Town", "Samanabad",
      // Commercial / Road Areas
      "Raiwind Road", "Multan Road", "Ferozpur Road", "Lahore-Islamabad Motorway",
      "Thokar Niaz Baig", "Ring Road Lahore", "Canal Road",
      "Bedian Road", "Airport Road", "Defence Road", "Walton Road",
      "Jail Road", "Main Bazar", "McLeod Road", "Abbot Road",
      "Garhi Shahu", "Mozang", "Chauburji", "Minar-e-Pakistan",
      "Barkat Market", "Hussain Chowk",
      "Ghazi Road", "Kanal Road", "Peco Road",
      // New Schemes
      "Pace Woodlands", "Ali Block Garden Town",
      "Rafi Block", "Talha Block", "Usman Block", "Nargis Block",
      "PIA Housing Scheme", "PAF Falcon Complex",
      "Lahore Askari Bypass", "New Lahore City",
      "Citi Housing Lahore", "Citi Housing Main Boulevard",
      "Royal Orchard Lahore", "Royal Residencia",
    ],
  },
  {
    name: "Karachi",
    localities: [
      // DHA
      "DHA Phase 1", "DHA Phase 2", "DHA Phase 2 Extension",
      "DHA Phase 3", "DHA Phase 4", "DHA Phase 5",
      "DHA Phase 5 Extension", "DHA Phase 6", "DHA Phase 6 Extension",
      "DHA Phase 7", "DHA Phase 7 Extension", "DHA Phase 8",
      "DHA Phase 8 Extension", "DHA City Karachi",
      "DHA Creek Anwar", "Creek Vista DHA",
      // Bahria Town
      "Bahria Town Karachi", "Bahria Town Precinct 1", "Bahria Town Precinct 2",
      "Bahria Town Precinct 10", "Bahria Town Precinct 11",
      "Bahria Town Precinct 12", "Bahria Town Precinct 15",
      "Bahria Town Precinct 19", "Bahria Town Precinct 25",
      "Bahria Town Precinct 27", "Bahria Town Precinct 31",
      "Bahria Sports City", "Bahria Paradise",
      // Clifton & Sea View
      "Clifton", "Clifton Block 1", "Clifton Block 2", "Clifton Block 3",
      "Clifton Block 4", "Clifton Block 5", "Clifton Block 7", "Clifton Block 8",
      "Clifton Block 9", "Sea View Apartments",
      "Boat Basin", "Bath Island", "Zamzama",
      // Gulshan-e-Iqbal
      "Gulshan-e-Iqbal", "Gulshan-e-Iqbal Block 1", "Gulshan-e-Iqbal Block 2",
      "Gulshan-e-Iqbal Block 3", "Gulshan-e-Iqbal Block 4",
      "Gulshan-e-Iqbal Block 5", "Gulshan-e-Iqbal Block 6",
      "Gulshan-e-Iqbal Block 7", "Gulshan-e-Iqbal Block 10",
      "Gulshan-e-Iqbal Block 13", "Gulshan-e-Iqbal Block 14",
      "Gulshan-e-Iqbal Block 16",
      // Gulistan-e-Jauhar
      "Gulistan-e-Jauhar", "Gulistan-e-Jauhar Block 1",
      "Gulistan-e-Jauhar Block 2", "Gulistan-e-Jauhar Block 3",
      "Gulistan-e-Jauhar Block 7", "Gulistan-e-Jauhar Block 12",
      "Gulistan-e-Jauhar Block 13", "Gulistan-e-Jauhar Block 14",
      "Gulistan-e-Jauhar Block 15", "Gulistan-e-Jauhar Block 16",
      "Gulistan-e-Jauhar Block 17", "Gulistan-e-Jauhar Block 18",
      "Gulistan-e-Jauhar Block 19", "Gulistan-e-Jauhar Block 20",
      // Nazimabad & North Nazimabad
      "North Nazimabad", "North Nazimabad Block A",
      "North Nazimabad Block B", "North Nazimabad Block C",
      "North Nazimabad Block D", "North Nazimabad Block F",
      "North Nazimabad Block H", "North Nazimabad Block J",
      "North Nazimabad Block K", "North Nazimabad Block L",
      "North Nazimabad Block N", "North Nazimabad Block R",
      "North Nazimabad Block S", "North Nazimabad Block T",
      "Nazimabad", "Nazimabad No. 1", "Nazimabad No. 2", "Nazimabad No. 3",
      "Nazimabad No. 4", "Naya Nazimabad",
      "Naya Nazimabad Block A", "Naya Nazimabad Block B",
      "Naya Nazimabad Block C", "Naya Nazimabad Block D",
      // PECHS
      "PECHS", "PECHS Block 2", "PECHS Block 3", "PECHS Block 6",
      "Bahadurabad", "Tariq Road", "Shaheed-e-Millat Road",
      // Korangi & Landhi
      "Korangi", "Korangi No. 1", "Korangi No. 2", "Korangi No. 4",
      "Korangi No. 5", "Korangi No. 6", "Korangi Industrial Area",
      "Korangi Crossing", "Landhi", "Landhi No. 1", "Landhi No. 2",
      "Landhi No. 3", "Landhi No. 4", "Landhi No. 5", "Landhi No. 6",
      "Quaidabad", "Steel Town",
      // Malir
      "Malir", "Malir Cantt", "Malir Extension", "Malir Halt",
      "Malir City", "Malir 15 No.", "Falcon Complex Malir",
      // Federal B Area
      "Federal B Area", "FB Area Block 1", "FB Area Block 2",
      "FB Area Block 3", "FB Area Block 7", "FB Area Block 10",
      "FB Area Block 13", "FB Area Block 14", "FB Area Block 16",
      // Schemes
      "Scheme 33", "Scheme 33 Sector 14", "Scheme 33 Sector 15",
      "Scheme 33 Sector 17", "Scheme 33 Sector 20",
      "Scheme 33 Sector 24", "Scheme 33 Sector 25",
      "Scheme 45", "Scheme 36",
      // Other Areas
      "Gadap Town", "Surjani Town", "Surjani Town Sector 1",
      "Surjani Town Sector 4", "Surjani Town Sector 7",
      "Taiser Town", "Taiser Town Sector 1",
      "Lyari", "Saddar", "I.I. Chundrigar Road",
      "Shahrah-e-Faisal", "University Road", "SITE Area",
      "Askari 4", "Askari 5", "Askari 3",
      "Saadi Town", "Saadi Town Block 3", "Saadi Town Block 5",
      "Safoora Goth", "Karachi Administration Society",
      "Model Colony", "Shah Faisal Colony",
      "Shah Faisal Colony Block 1", "Shah Faisal Colony Block 4",
      "Kemari", "Bin Qasim", "Port Qasim",
      "Orangi Town", "Orangi Town Sector 5",
      "Liaquatabad", "Liaquatabad Block 1", "Liaquatabad Block 7",
      "Buffer Zone", "New Karachi",
      "New Karachi Industrial Area", "Metroville",
      "Gulshan-e-Hadeed Phase 1", "Gulshan-e-Hadeed Phase 2",
      "Gulshan-e-Maymar", "Gulzar-e-Hijri",
      "KDA Officers Society", "Navy Housing Scheme Karsaz",
      "Cantt", "Clifton Cantt",
      "Rashid Minhas Road", "Shahra-e-Quaideen",
      "PIB Colony", "Soldier Bazaar", "Garden East", "Garden West",
      "Jamshed Town", "Jamshed Road",
      "Guru Mandir", "Burns Garden", "Lalukhet",
      "Pakistan Chowk", "Tower", "Lines Area",
    ],
  },
  {
    name: "Islamabad",
    localities: [
      // F Sectors
      "F-5", "F-6", "F-6 (Super Market)", "F-6/1", "F-6/2", "F-6/3", "F-6/4",
      "F-7", "F-7/1", "F-7/2", "F-7/3", "F-7/4", "F-7 Markaz",
      "F-8", "F-8/1", "F-8/2", "F-8/3", "F-8/4", "F-8 Markaz",
      "F-9 (Fatima Jinnah Park)", "F-10", "F-10/1", "F-10/2", "F-10/3", "F-10/4",
      "F-10 Markaz", "F-11", "F-11/1", "F-11/2", "F-11/3", "F-11/4",
      "F-11 Markaz", "F-12", "F-15", "F-16", "F-17",
      // E Sectors
      "E-7", "E-7/1", "E-7/2", "E-7/3",
      "E-11", "E-11/1", "E-11/2", "E-11/3", "E-11/4",
      "E-12", "E-16", "E-17",
      // G Sectors
      "G-5", "G-6", "G-6/1", "G-6/2", "G-6/3", "G-6/4",
      "G-7", "G-7/1", "G-7/2", "G-7/3", "G-7/4",
      "G-8", "G-8/1", "G-8/2", "G-8/4", "G-8 Markaz",
      "G-9", "G-9/1", "G-9/2", "G-9/3", "G-9/4", "G-9 Markaz",
      "G-10", "G-10/1", "G-10/2", "G-10/3", "G-10/4", "G-10 Markaz",
      "G-11", "G-11/1", "G-11/2", "G-11/3", "G-11/4", "G-11 Markaz",
      "G-12", "G-13", "G-13/1", "G-13/2", "G-13/3", "G-13/4",
      "G-14", "G-14/1", "G-14/2", "G-14/3", "G-14/4",
      "G-15", "G-15/1", "G-15/2", "G-15/3", "G-15/4",
      "G-16", "G-17",
      // I Sectors
      "I-8", "I-8/1", "I-8/2", "I-8/3", "I-8/4", "I-8 Markaz",
      "I-9", "I-9/1", "I-9/2", "I-9/3", "I-9/4", "I-9 Industrial Area",
      "I-10", "I-10/1", "I-10/2", "I-10/3", "I-10/4", "I-10 Markaz",
      "I-11", "I-12", "I-14", "I-14/1", "I-14/2", "I-14/3", "I-14/4",
      "I-15", "I-16", "I-16/1", "I-16/2", "I-16/3", "I-16/4",
      // D & H Sectors
      "D-12", "D-12/1", "D-12/2", "D-12/3", "D-12/4",
      "D-17", "D-17/1", "D-17/2", "D-18",
      "H-8", "H-8/1", "H-8/2", "H-8/3", "H-8/4",
      "H-9", "H-10", "H-11", "H-12", "H-13",
      "H-13/1", "H-13/2", "H-13/3", "H-13/4",
      // B & C Sectors
      "B-17", "B-17 MPCHS", "C-16", "C-18",
      // Blue Area & Commercial
      "Blue Area", "Jinnah Avenue", "Jinnah Super Market",
      "Kohsar Market F-6", "Super Market F-6", "Melody Market G-6",
      "Aabpara Market G-6", "Centaurus Mall",
      // DHA Islamabad
      "DHA Phase 1 Islamabad", "DHA Phase 1 Sector A",
      "DHA Phase 1 Sector B", "DHA Phase 1 Sector C",
      "DHA Phase 1 Sector D", "DHA Phase 1 Sector E",
      "DHA Phase 1 Sector F", "DHA Phase 2 Islamabad",
      "DHA Phase 2 Sector A", "DHA Phase 2 Sector B",
      "DHA Phase 2 Sector D", "DHA Phase 2 Sector E",
      "DHA Phase 2 Sector H", "DHA Phase 2 Sector J",
      "DHA Phase 5 Islamabad",
      // Bahria Town
      "Bahria Town Phase 1", "Bahria Town Phase 2", "Bahria Town Phase 3",
      "Bahria Town Phase 4", "Bahria Town Phase 5", "Bahria Town Phase 6",
      "Bahria Town Phase 7", "Bahria Town Phase 8",
      "Bahria Town Phase 8 Safari Valley", "Bahria Town Phase 8 Lake View",
      "Bahria Enclave", "Bahria Enclave Sector A",
      "Bahria Enclave Sector B", "Bahria Enclave Sector C",
      "Bahria Enclave Sector F", "Bahria Enclave Sector G",
      "Bahria Enclave Sector H", "Bahria Garden City",
      "Bahria Spring", "Bahria Heights",
      // Other Housing Schemes
      "Pakistan Town Phase 1", "Pakistan Town Phase 2",
      "CBR Town Phase 1", "CBR Town Phase 2",
      "PWD Housing Society", "PWD Block A", "PWD Block B", "PWD Block C", "PWD Block D",
      "Soan Garden", "Soan Garden Block A", "Soan Garden Block H",
      "Multi Gardens Phase 1", "Multi Gardens Phase 2",
      "Top City-1", "Top City Block A",
      "Capital Smart City", "Park View City",
      "Park View City Islamabad", "Faisal Town Islamabad",
      "Navy Anchorage", "River Garden",
      "National Police Foundation", "NPF O-9",
      "Diplomatic Enclave", "Constitution Avenue",
      // Margalla & Nature
      "Margalla Hills", "Margalla Town Phase 1", "Margalla Town Phase 2",
      "Bani Gala", "Chak Shahzad",
      "Simly Dam Road", "Lehtrar Road",
      // Peripheral
      "Golra", "Golra Mor", "Tarnol", "Taxila Road",
      "Kashmir Highway", "Islamabad Expressway",
      "Zero Point", "Faizabad", "Koral Chowk",
      "Bhara Kahu", "Phulgran", "Sohan",
      "Rawat Islamabad", "Humak",
      "Islamabad Highway", "Srinagar Highway",
      "Khanna Pul", "Gangal",
    ],
  },
  {
    name: "Rawalpindi",
    localities: [
      // Bahria Town
      "Bahria Town Phase 1", "Bahria Town Phase 2", "Bahria Town Phase 3",
      "Bahria Town Phase 4", "Bahria Town Phase 5", "Bahria Town Phase 6",
      "Bahria Town Phase 7", "Bahria Town Phase 8",
      "Bahria Town Phase 8 Ali Block", "Bahria Town Phase 8 Umer Block",
      "Bahria Town Phase 8 Awami Villas",
      "Bahria Greens", "Bahria Heights Rawalpindi",
      // DHA
      "DHA Phase 1 Rawalpindi", "DHA Phase 2 Rawalpindi",
      "DHA Phase 3 Rawalpindi",
      // Satellite Town
      "Satellite Town", "Satellite Town Block A", "Satellite Town Block B",
      "Satellite Town Block C", "Satellite Town Block D",
      "Satellite Town Block E", "Satellite Town Block F",
      // Cantt
      "Cantt", "Chaklala Cantt", "Chaklala Scheme 1",
      "Chaklala Scheme 2", "Chaklala Scheme 3",
      // Askari
      "Askari 1", "Askari 2", "Askari 3", "Askari 4",
      "Askari 5", "Askari 7", "Askari 10", "Askari 11", "Askari 14",
      // Commercial & Old City
      "Saddar", "Committee Chowk", "Raja Bazaar",
      "Westridge", "Westridge Block 1", "Westridge Block 2", "Westridge Block 3",
      "Lalazar", "New Lalazar",
      "Shamsabad", "Pirwadhai",
      "Adiala Road", "Adyala Town",
      "Airport Housing Society",
      "Gulraiz Housing Society Phase 1", "Gulraiz Housing Society Phase 2",
      "Gulraiz Housing Society Phase 3",
      "Gulzar-e-Quaid", "Media Town",
      "PWD Housing Scheme", "PWD Block A", "PWD Block B",
      // Roads & Areas
      "Murree Road", "Peshawar Road", "GT Road", "Mall Road",
      "Range Road", "Benazir Bhutto Road", "Tipu Road",
      "Morgah", "Dhoke Kala Khan", "Dhoke Mangtal",
      "6th Road", "Chur Chowk", "Tramri Chowk",
      "Rawat", "Kallar Syedan", "Taxila", "Wah Cantt",
      "Misryal Road", "Asghar Mall Road", "Bank Road",
      "Arya Mohalla", "Banni", "Tench Bhatta",
      "Khayaban-e-Sir Syed", "Race Course Road",
      "Gulistan Colony", "Muslim Town",
      "Liaquat Bagh", "Allahabad",
      "Shah Khalid Colony", "Dhoke Kashmirian",
      "Rawalpindi Cantt Bazaar", "Harley Street",
      "Citi Housing Rawalpindi",
      "Royal Avenue", "Royal Residencia Rawalpindi",
    ],
  },
  {
    name: "Faisalabad",
    localities: [
      // Peoples Colony
      "Peoples Colony No. 1", "Peoples Colony No. 2",
      "Peoples Colony Block A", "Peoples Colony Block B",
      // Housing Schemes
      "Madina Town", "Madina Town Block A", "Madina Town Block B",
      "Eden Valley", "Eden Valley Block A", "Eden Valley Block B",
      "Eden Garden", "Eden Abad", "Eden Executive Extension",
      "Eden Lane Villas", "Eden Orchard Faisalabad",
      "Gulberg Colony", "Gulistan Colony",
      "Jinnah Colony", "Jinnah Garden",
      "Ghulam Muhammad Abad", "Ghulam Muhammad Abad Block A",
      "Samanabad", "Samanabad Block A",
      "Millat Town", "Millat Town Block A", "Millat Town Block B",
      "Citi Housing Faisalabad", "Citi Housing Phase 1", "Citi Housing Phase 2",
      "Royal Orchard", "Royal Orchard Block A", "Royal Orchard Block B",
      "Kohinoor City", "Kohinoor Town",
      "Wapda Town Faisalabad", "Wapda Town Phase 1", "Wapda Town Phase 2",
      "Canal Heights", "Canal Garden Faisalabad",
      "Officers Colony", "Officers Colony Block A",
      "National Bank Colony", "Railway Colony",
      // Roads
      "Canal Road", "Sargodha Road", "Jaranwala Road",
      "D Ground", "D Ground Sargodha Road", "Satiana Road",
      "Susan Road", "Susan Road Block A",
      "Batala Colony", "Civil Lines", "Zila Council Colony",
      "Abdullah Pur", "Dijkot Road",
      "Jhang Road", "Narwala Road", "Samundri Road",
      "Millat Road", "Club Road",
      "Abdullahpur", "Chak Jhumra",
      // Towns & Commercial
      "Faisalabad Serena", "Allied Colony",
      "Muslim Town", "Taj Colony",
      "Lasani Town", "Al-Noor Town",
      "Sheikhupura Road", "Chiniot Bazaar Road",
      "Amin Town", "Salem Town", "Sir Syed Town",
      "Rachna Town", "Green Town", "Raza Abad",
      "Model City Faisalabad", "Lahore Road",
      "Faisalabad Smart City", "Garden Colony",
    ],
  },
  {
    name: "Multan",
    localities: [
      // DHA & Bahria
      "DHA Multan", "DHA Multan Phase 1", "DHA Multan Phase 1 Sector A",
      "DHA Multan Phase 1 Sector B", "DHA Multan Phase 1 Sector C",
      "DHA Multan Phase 1 Sector D", "DHA Multan Phase 1 Sector E",
      "DHA Multan Phase 1 Sector F", "DHA Multan Phase 2",
      "DHA Villas Multan",
      "Bahria Town Multan", "Bahria Town Multan Sector A",
      "Bahria Town Multan Sector B", "Bahria Town Multan Sector C",
      "Bahria Town Multan Sector D", "Bahria Town Multan Sector E",
      "Bahria Town Multan Sector F",
      // Main Localities
      "Bosan Road", "Nishtar Road", "MDA Chowk",
      "Shah Rukn-e-Alam Colony", "Shah Rukn-e-Alam Colony Block A",
      "Shah Rukn-e-Alam Colony Block B", "Shah Rukn-e-Alam Colony Block C",
      "Gulgasht Colony", "Gulgasht Colony Block A",
      "Officers Colony", "Officers Colony Block A",
      "Model Town A", "Model Town B", "Model Town C",
      "Cantt", "Cantt Multan", "Sher Shah Road",
      "Vehari Road", "Khanewal Road", "Bosan Road Chowk",
      "Wapda Town Multan", "Garden Town Multan",
      "New Multan", "New Multan Phase 1", "New Multan Phase 2",
      "Southern Bypass Multan",
      "Royal Orchard Multan", "Citi Housing Multan",
      "Buch Villas", "Buch Executive Villas",
      "Buch Villas Phase 1", "Buch Villas Phase 2",
      // Additional
      "Mumtazabad Colony", "Gulgasht Extension",
      "Hussain Agahi", "Old Shujabad Road",
      "Suraj Miani Road", "Abdali Road",
      "Tariqabad", "Chungi No. 9",
      "Industrial Estate Multan", "Northern Bypass",
      "Sher Shah Colony", "Qasim Bela",
      "Nawab Colony", "Rasheedabad",
      "Qasba Maral", "BZU Road",
      "Shamsabad Colony Multan", "Samijabad",
      "Pak Gate", "Delhi Gate", "Haram Gate",
      "Muslim Town Multan", "Masoom Shah Road",
    ],
  },
  {
    name: "Peshawar",
    localities: [
      // Hayatabad
      "Hayatabad Phase 1", "Hayatabad Phase 2", "Hayatabad Phase 3",
      "Hayatabad Phase 4", "Hayatabad Phase 5", "Hayatabad Phase 5 Sector E-5",
      "Hayatabad Phase 6", "Hayatabad Phase 6 Sector E-6",
      "Hayatabad Phase 7", "Hayatabad Phase 7 Sector E-7",
      "Hayatabad Industrial Estate",
      // DHA & Askari
      "DHA Peshawar Phase 1", "DHA Peshawar Phase 1 Sector A",
      "DHA Peshawar Phase 1 Sector B", "DHA Peshawar Phase 1 Sector C",
      "DHA Peshawar Phase 1 Sector D", "DHA Peshawar Phase 1 Sector E",
      "DHA Peshawar Phase 1 Sector F",
      "Askari 5 Peshawar", "Askari 6 Peshawar",
      // Main Areas
      "University Town", "University Town Block A", "University Town Block B",
      "University Road", "Peshawar University Campus",
      "Regi Model Town", "Regi Model Town Phase 1",
      "Regi Model Town Phase 2", "Regi Model Town Phase 3",
      "Regi Model Town Phase 4", "Regi Model Town Phase 5",
      "Gulbahar", "Gulbahar Colony",
      "Saddar", "Saddar Bazaar Peshawar",
      "Cantt", "Cantt Peshawar", "The Mall Peshawar",
      "Warsak Road", "GT Road Peshawar", "Ring Road Peshawar",
      "Board Bazaar", "Kohat Road", "Charsadda Road",
      "Dalazak Road", "Jamrud Road",
      // Towns & Colonies
      "Town", "Old City", "Qissa Khwani Bazaar",
      "Shami Road", "Abdara Road", "Circular Road",
      "Wazir Bagh", "Arbab Road", "Shaheen Town",
      "Chamkani", "Mattani", "Bara Road",
      "Khyber Colony", "Frontier Colony",
      "PAF Colony", "PAC Kamra Road",
      "Danish Abad", "Rashid Garhi",
      "Tehkal", "Tehkal Payan", "Tehkal Bala",
      "Palosai", "Rahat Abad",
      "Phase 3 Town", "Mall of Peshawar Road",
      "Pishtakhara", "Badaber Road",
      "Northern Bypass", "Southern Bypass",
      "Peshawar Cantt Bazaar", "Nothia Bazaar",
    ],
  },
  {
    name: "Quetta",
    localities: [
      "Satellite Town", "Satellite Town Block 1", "Satellite Town Block 2",
      "Satellite Town Block 3", "Satellite Town Block 4",
      "Jinnah Town", "Jinnah Town Phase 1", "Jinnah Town Phase 2",
      "Cantt", "Quetta Cantt",
      "Zarghoon Road", "Zarghoon Road Block A",
      "Samungli Road", "Airport Road Quetta",
      "Brewery Road", "Sariab Road", "Sariab Mills",
      "Double Road", "Hali Road",
      "Joint Road", "Staff College Road",
      "Nawa Killi", "Pashtoonabad", "Pashtoonabad Block A",
      "Chiltan Housing Scheme", "Chiltan Housing Phase 1",
      "Arbab Karam Khan Road", "Mano Jan Road",
      "Lytton Road", "Circular Road Quetta",
      "Railway Housing Colony", "PDA Housing Scheme",
      "Model Town Quetta", "Civil Lines Quetta",
      "Sabzal Road", "Spiny Road",
      "Gulistan Town", "Killi Ismail",
      "Kuchlak Road", "Mastung Road",
      "Mariabad", "Hazara Town Quetta",
      "Shahbaz Town", "Eastern Bypass Quetta",
      "Baleli", "Hanna Lake Road",
      "GOR Colony", "Fort Munro Road",
    ],
  },
  {
    name: "Sialkot",
    localities: [
      "Cantt", "Sialkot Cantt",
      "Paris Road", "Kachehri Road",
      "Defence Road Sialkot", "Kashmir Road",
      "Model Town", "Model Town Block A", "Model Town Block B",
      "Gulberg", "Gulberg Colony Sialkot",
      "Allama Iqbal Shahrah", "Civil Lines",
      "Rangpura", "Hajipura", "Khawaja Safdar Road",
      "Wazirabad Road", "Daska Road", "Pasrur Road",
      "Satellite Town Sialkot", "PAF Colony Sialkot",
      "Head Marala Road", "Shahabpura",
      "Mohalla Islam Pura", "Ugoki Road",
      "Trunk Bazaar", "City Center Sialkot",
      "Defence Housing Colony", "Officers Colony Sialkot",
      "Jinnah Park Road", "Circular Road Sialkot",
      "Neka Pura", "Kotli Loharan",
      "Sambrial", "Sambrial Road",
      "Wazirabad", "Airport Road Sialkot",
    ],
  },
  {
    name: "Gujranwala",
    localities: [
      "Satellite Town", "Satellite Town Block A", "Satellite Town Block B",
      "Model Town", "Model Town Block A", "Model Town Block B",
      "Peoples Colony", "Peoples Colony Block A",
      "Civil Lines", "Civil Lines Block 1",
      "Trust Plaza Road", "GT Road Gujranwala",
      "DC Colony", "DC Colony Phase 1", "DC Colony Phase 2",
      "Citi Housing Gujranwala", "Citi Housing Block A",
      "Palm City", "Master City", "Master City Block A",
      "Garden Town Gujranwala", "Wapda Town Gujranwala",
      "Officers Colony Gujranwala",
      "Cantt Gujranwala", "Cantt Bazaar",
      "Hafizabad Road", "Sialkot Road",
      "Pasrur Road", "Sheikhupura Road Gujranwala",
      "Gondlanwala Road", "Circular Road Gujranwala",
      "Eminabad Road", "Qila Didar Singh Road",
      "Green Town Gujranwala", "Gulshan Colony",
      "Gill Road", "Railway Road",
      "Citi Housing Phase 2", "Dream Gardens",
      "Royal Orchard Gujranwala", "Nawab Colony Gujranwala",
    ],
  },
  {
    name: "Hyderabad",
    localities: [
      "Latifabad", "Latifabad Unit 1", "Latifabad Unit 2",
      "Latifabad Unit 3", "Latifabad Unit 4", "Latifabad Unit 5",
      "Latifabad Unit 6", "Latifabad Unit 7", "Latifabad Unit 8",
      "Latifabad Unit 9", "Latifabad Unit 10", "Latifabad Unit 11",
      "Latifabad Unit 12",
      "Qasimabad", "Qasimabad Phase 1", "Qasimabad Phase 2",
      "Gulshan-e-Shahbaz", "Gulshan-e-Shahbaz Phase 1",
      "Auto Bhan Road", "Bypass Hyderabad", "National Highway",
      "Cantt", "Saddar Hyderabad",
      "Heerabad", "Paretabad",
      "Hirabad", "Tilak Incline",
      "Market Road", "Station Road Hyderabad",
      "Phuleli Canal Road", "Tando Muhammad Khan Road",
      "Citizen Colony", "Naseem Nagar",
      "Wahdat Colony", "Sindh University Road",
      "GOR Colony Hyderabad", "SITE Area Hyderabad",
      "Civil Lines Hyderabad", "Kohsar Colony",
      "Model Town Hyderabad", "DHA Hyderabad",
      "Hussainabad Hyderabad", "Fakir Ka Pir Road",
    ],
  },
  {
    name: "Bahawalpur",
    localities: [
      "Model Town A", "Model Town B", "Model Town C",
      "Satellite Town", "Satellite Town Phase 1", "Satellite Town Phase 2",
      "Baghdad Road", "Baghdad Colony",
      "Circular Road", "Yazman Road",
      "Hasilpur Road", "University Chowk",
      "Cantt Bahawalpur", "Farid Gate",
      "Civil Lines Bahawalpur", "Officers Colony Bahawalpur",
      "Gulberg Colony Bahawalpur", "Shahi Bazaar",
      "Railway Road Bahawalpur", "Ahmed Pur Road",
      "Dera Nawab Road", "Allahabad Colony",
      "Qasrani Colony", "Noor Mahal Road",
      "Abbasia Town", "Wapda Colony Bahawalpur",
      "DC Colony Bahawalpur", "Victoria Park",
      "One Unit Chowk", "Chungi No. 14",
    ],
  },
  {
    name: "Gujrat",
    localities: [
      "Bhimber Road", "Jalalpur Jattan Road",
      "GT Road Gujrat", "Civil Lines Gujrat",
      "Cantt Gujrat", "Model Town Gujrat",
      "Satellite Town Gujrat", "Lala Musa Road",
      "Sara-e-Alamgir Road", "Kharian Road",
      "Railway Road Gujrat", "Circular Road Gujrat",
      "Peoples Colony Gujrat", "Officers Colony Gujrat",
      "Jinnah Road Gujrat", "Dinga Road",
      "Kunjah Road", "Gujrat Bypass",
      "University Road Gujrat", "GTS Chowk",
    ],
  },
  {
    name: "Sargodha",
    localities: [
      "Satellite Town", "Satellite Town Block A", "Satellite Town Block B",
      "University Road Sargodha", "University of Sargodha",
      "Cantt Sargodha", "Civil Lines Sargodha",
      "Block 15", "Block 17", "Block 22", "Block 23",
      "Block 24", "Block 25", "Block 27",
      "Bhalwal Road", "Sillanwali Road",
      "Faisalabad Road Sargodha", "Lahore Road Sargodha",
      "Mianwali Road", "Khushab Road",
      "Peoples Colony Sargodha", "Model Town Sargodha",
      "Officers Colony Sargodha", "PAF Colony Sargodha",
      "GOR Colony Sargodha", "Wapda Town Sargodha",
      "Railway Road Sargodha", "Queens Road",
      "Circular Road Sargodha", "Mall Road Sargodha",
      "Jail Road Sargodha", "Pul Maan Road",
      "Canal Colony Sargodha", "Muslim Town Sargodha",
    ],
  },
  {
    name: "Abbottabad",
    localities: [
      "Jinnahabad", "Supply", "Supply Bazaar",
      "Mandian", "Mandian Road",
      "Nawanshehr", "Nawanshehr Colony",
      "Cantt Abbottabad", "Abbottabad Cantt",
      "Ilyasi Masjid Road", "Mansehra Road",
      "Link Road", "Link Road Colony",
      "Havelian", "Havelian Bypass",
      "Shimla Hill", "Shimla Hill Colony",
      "Sarban Hills", "PMA Road",
      "Kakul Road", "Kakul",
      "Jhangi Syedan", "Nawan Shehr",
      "Kehal", "Ilyasi Mosque Area",
      "Officers Colony Abbottabad", "Mirpur Abbottabad",
      "Township Abbottabad", "Bilal Town",
      "Ayub Medical Complex Road", "Malikpura",
      "Kunj Qadeem", "Pine Hills",
    ],
  },
  {
    name: "Mardan",
    localities: [
      "Cantt Mardan", "Mardan Cantt",
      "Sheikh Maltoon Town", "Sheikh Maltoon Town Phase 1",
      "Sheikh Maltoon Town Phase 2",
      "Bank Road Mardan", "Nowshera Road",
      "Shamsi Road", "Par Hoti",
      "Canal Road Mardan", "Civil Colony Mardan",
      "Baghdada", "Muslim Abad",
      "Sikandara", "Katlang Road",
      "Malakand Road", "Swabi Road",
      "Gaju Khan Medical College Road",
      "Rustam Road", "Hoti Road",
      "Officers Colony Mardan", "Teachers Colony",
      "Railway Road Mardan", "University Road Mardan",
    ],
  },
  {
    name: "Sukkur",
    localities: [
      "Barrage Colony", "Military Road",
      "Airport Road Sukkur", "Cantt Sukkur",
      "New Sukkur", "Old Sukkur", "Rohri",
      "Station Road Sukkur", "Labour Colony",
      "Shikarpur Road", "Civil Lines Sukkur",
      "Minara Road", "Ayub Gate",
      "Lansdowne Road", "Clock Tower Area",
      "Sukkur Bypass", "National Highway Sukkur",
      "Adam Shah Colony", "Hussainabad Sukkur",
      "Ghouspur Road", "Pano Aqil Road",
    ],
  },
  {
    name: "Larkana",
    localities: [
      "Jinnah Bagh Road", "Station Road Larkana",
      "VIP Road Larkana", "Cantt Larkana",
      "Naudero Road", "Mohenjo Daro Road",
      "Civil Lines Larkana", "Sachal Colony",
      "Bunder Road Larkana", "New Dadu Road",
      "Ratodero Road", "Bakrani Road",
      "Officers Colony Larkana", "Model Town Larkana",
      "Resham Gali", "Shahra-e-Liaquat",
      "Gharibabad", "Ali Town Larkana",
    ],
  },
  {
    name: "Sahiwal",
    localities: [
      "Farid Town", "Farid Town Block A", "Farid Town Block B",
      "Model Town Sahiwal", "Model Town Phase 1", "Model Town Phase 2",
      "High Court Road", "Pakpattan Road",
      "Canal Colony", "Canal Colony Phase 1",
      "Officers Colony Sahiwal",
      "Cantt Sahiwal", "Civil Lines Sahiwal",
      "Noor Shah Road", "Railway Road Sahiwal",
      "Faisal Colony Sahiwal", "Harappa Road",
      "Chichawatni Road", "Arifwala Road",
      "GT Road Sahiwal", "Bypass Sahiwal",
      "Muslim Town Sahiwal", "Peoples Colony Sahiwal",
      "Satellite Town Sahiwal", "Township Sahiwal",
    ],
  },
  {
    name: "Dera Ghazi Khan",
    localities: [
      "City Center", "Cantt DG Khan",
      "Jampur Road", "Civil Lines DG Khan",
      "Sakhi Sarwar Road", "Taunsa Road",
      "Block 1", "Block 2", "Block 3",
      "Block 10", "Block 12", "Block 14",
      "Officers Colony DG Khan", "Model Town DG Khan",
      "PAF Colony DG Khan", "Railway Colony DG Khan",
      "University Road DG Khan", "College Road",
      "Hospital Road DG Khan", "Circular Road DG Khan",
      "Airport Road DG Khan", "Chowk Bazar",
    ],
  },
  {
    name: "Mirpur (AJK)",
    localities: [
      "Sector F-1", "Sector F-2", "Sector F-3", "Sector F-4",
      "Sector B-1", "Sector B-2", "Sector B-3",
      "Sector C-1", "Sector C-2",
      "Allama Iqbal Road", "New City Mirpur",
      "Kotli Road", "Mangla", "Mangla Cantt",
      "Chowk Shaheedan", "Ali Market",
      "Dadyal", "Islamgarh Road",
      "Mirpur Bypass", "Old City Mirpur",
      "Bhimber Road Mirpur", "Jari Kas",
      "Model Town Mirpur", "Officers Colony Mirpur",
      "Khari Sharif Road", "Afzalpur",
    ],
  },
  {
    name: "Muzaffarabad",
    localities: [
      "Upper Chattar", "Lower Chattar", "Chattar Klass",
      "CMH Road", "Domel", "Domel Chowk",
      "Pir Chinasi Road", "Chella Bandi",
      "Garhi Dupatta", "Garhi Habibullah",
      "Nawan Shehr Muzaffarabad", "Madina Market",
      "Link Road Muzaffarabad", "Neelum Road",
      "Kohala Bridge Road", "Ambore",
      "Dulai", "Langerpura",
      "Civil Lines Muzaffarabad", "Officers Colony Muzaffarabad",
      "Jalalabad", "Kachehri Road",
      "Airport Road Muzaffarabad", "Red Cross Road",
    ],
  },
  {
    name: "Gilgit",
    localities: [
      "Jutial", "Jutial Upper", "Jutial Lower",
      "Kashrote", "Kashrote Bazar",
      "Zulfiqarabad", "Basin", "Basin Road",
      "Airport Road Gilgit", "Danyore",
      "Danyore Link Road", "NLI Market",
      "Aga Khan Shahi Qila", "River Road",
      "Babar Road", "Shahrah-e-Quaid-e-Azam",
      "Konodas", "Sonikot", "Sultanabad",
      "Khomer", "Barmas", "Napura",
      "Chinar Bagh", "Saddar Bazaar Gilgit",
      "City Center Gilgit", "Cinema Bazaar",
    ],
  },
  {
    name: "Skardu",
    localities: [
      "Hussainabad", "Hussainabad Road",
      "Hoto", "Hoto Skardu",
      "Yadgar Chowk", "New Bazaar",
      "Old Bazaar Skardu", "Raja Bazaar Skardu",
      "Skardu Airport Road", "Link Road Skardu",
      "Ali Abad", "Naya Bazar",
      "Kachura", "Shangrila Road",
      "Satpara Road", "Sadpara",
      "College Road Skardu", "Hospital Road Skardu",
    ],
  },
  {
    name: "Chitral",
    localities: [
      "Shahi Bazaar", "Ataliq Bazaar",
      "Danin", "Jang Bazar",
      "Chitral Airport Road", "Drosh Road",
      "Shahi Mosque Road", "River Road Chitral",
      "Broze", "Jughor",
      "Singoor", "Birmoghlasht Road",
      "Old Bazaar Chitral", "Booni Road",
      "Civil Lines Chitral", "New Town Chitral",
    ],
  },
  {
    name: "Swat (Mingora)",
    localities: [
      "Saidu Sharif", "Saidu Sharif Hospital Road",
      "Mingora City", "Mingora Bypass",
      "Fizagat", "Fizagat Park Road",
      "GT Road Swat", "GT Road Mingora",
      "Malam Jabba Road", "Kanju",
      "Bahrain Road", "Madyan Road",
      "Green Chowk", "Nishat Chowk",
      "Haji Baba Road", "Qambar",
      "Manglawar", "Kooz Kalam",
      "Saidu Baba Road", "Rahim Abad",
      "Sangota", "Kabal Road",
      "Swat University Road", "Guli Bagh",
      "Matta Road", "Charbagh Road",
    ],
  },
  {
    name: "Dera Ismail Khan",
    localities: [
      "Cantt DI Khan", "Circular Road DI Khan",
      "Topanwala Road", "Civil Lines DI Khan",
      "Tank Road", "Daraban Road",
      "Paroa Road", "Sheikh Yusuf Road",
      "Qureshi Mohalla", "Officers Colony DI Khan",
      "Model Town DI Khan", "University Road DI Khan",
      "Canal Road DI Khan", "GT Road DI Khan",
      "Awan Colony", "Saddar Bazaar DI Khan",
      "City Center DI Khan", "Railway Road DI Khan",
    ],
  },
  {
    name: "Bannu",
    localities: [
      "Cantt Bannu", "Domel Road",
      "Miryan Road", "Civil Colony Bannu",
      "Lakki Road", "Kohat Road Bannu",
      "GT Road Bannu", "Circular Road Bannu",
      "City Center Bannu", "Officers Colony Bannu",
      "Model Town Bannu", "Saddar Bazaar Bannu",
      "Ahmadzai Colony", "Haji Camp Road",
      "University Road Bannu", "Hospital Road Bannu",
      "Jani Khel Road", "Baka Khel Road",
    ],
  },
  {
    name: "Kohat",
    localities: [
      "Cantt Kohat", "KDA Officers Colony",
      "Jarma", "Hangu Road",
      "Rawalpindi Road Kohat", "Peshawar Road Kohat",
      "Tirah Road", "Lachi Road",
      "Darra Adam Khel Road", "Kohat Bypass",
      "University Road Kohat", "CMH Road Kohat",
      "City Center Kohat", "Railway Road Kohat",
      "PAF Colony Kohat", "Officers Colony Kohat",
      "Model Town Kohat", "Civil Lines Kohat",
      "Shakardara Road", "Toi Bazaar",
    ],
  },
  {
    name: "Turbat",
    localities: [
      "Main Bazaar Turbat", "Airport Road Turbat",
      "Kech Housing Scheme", "Absar",
      "Absar Colony", "Dasht Road",
      "City Center Turbat", "Hospital Road Turbat",
      "University Road Turbat", "National Highway Turbat",
      "College Road Turbat", "Civil Lines Turbat",
      "Hoshab Road", "Tump Road",
      "Old Town Turbat", "New Town Turbat",
    ],
  },
  {
    name: "Gwadar",
    localities: [
      "Marine Drive", "Sangar Housing Scheme",
      "New Town Gwadar", "East Bay",
      "Gwadar Free Zone", "Old Town Gwadar",
      "West Bay", "Fish Harbour Road",
      "Airport Road Gwadar", "Coastal Highway",
      "Padi Zir", "Surbandar Road",
      "GDA Housing Scheme", "Singhar Housing Scheme",
      "Balochistan Coastal Development Road",
      "Port Area", "Koh-e-Batil",
      "Jewani Road", "Gwadar Smart Port City",
    ],
  },
  {
    name: "Zhob",
    localities: [
      "Main Bazaar Zhob", "Cantt Zhob",
      "Civil Lines Zhob", "Hospital Road Zhob",
      "Loralai Road", "Quetta Road Zhob",
      "Mughal Kot Road", "DI Khan Road",
      "FC Colony", "Officers Colony Zhob",
      "City Center Zhob", "Stadium Road",
      "University Road Zhob", "Kakar Colony",
    ],
  },
  {
    name: "Nawabshah (Shaheed Benazirabad)",
    localities: [
      "Sakrand Road", "Civil Lines Nawabshah",
      "Qazi Ahmed Road", "VIP Road Nawabshah",
      "Daur Road", "Station Road Nawabshah",
      "Cantt Nawabshah", "Model Town Nawabshah",
      "Officers Colony Nawabshah", "Peoples Colony Nawabshah",
      "Block A Nawabshah", "Block B Nawabshah",
      "Hospital Road Nawabshah", "University Road Nawabshah",
      "Bypass Nawabshah", "New Bus Stand Road",
      "Old Bus Stand Area", "Kazi Colony",
    ],
  },
  {
    name: "Khairpur",
    localities: [
      "Faiz Mahal Road", "Civil Lines Khairpur",
      "Thari Mirwah Road", "Station Road Khairpur",
      "Cantt Khairpur", "Model Town Khairpur",
      "Gambat Road", "Sukkur Road Khairpur",
      "Kot Diji Road", "Sobhani Road",
      "Officers Colony Khairpur", "New Housing Scheme",
      "University Road Khairpur", "Hospital Road Khairpur",
      "Bypass Khairpur", "City Center Khairpur",
    ],
  },
  {
    name: "Jhelum",
    localities: [
      "Cantt Jhelum", "Civil Lines Jhelum",
      "GT Road Jhelum", "Sarai Alamgir Road",
      "Beacon House Road", "Satellite Town Jhelum",
      "Model Town Jhelum", "Lala Musa Road Jhelum",
      "Chotala Road", "Shahpur Road",
      "Sanghoi Road", "Domeli Road",
      "Officers Colony Jhelum", "PAF Colony Jhelum",
      "Mall Road Jhelum", "Railway Road Jhelum",
      "Old City Jhelum", "GTS Chowk Jhelum",
      "Gulshan Colony Jhelum", "Muslim Town Jhelum",
    ],
  },
  {
    name: "Chakwal",
    localities: [
      "Talagang Road", "Cantt Chakwal",
      "Hospital Road Chakwal", "Main Bazaar Chakwal",
      "Civil Lines Chakwal", "Model Town Chakwal",
      "Officers Colony Chakwal", "Jhelum Road",
      "Rawalpindi Road Chakwal", "Dhudial Road",
      "Choa Saidan Shah Road", "Kallar Kahar Road",
      "University Road Chakwal", "Satellite Town Chakwal",
      "City Center Chakwal", "College Road Chakwal",
      "Lawa Road", "Balkassar Road",
    ],
  },
  {
    name: "Attock",
    localities: [
      "Cantt Attock", "Kamra", "Kamra Cantt",
      "Hazro", "Hazro City",
      "Fatehjang Road", "Fatehjang",
      "Rawalpindi Road Attock", "GT Road Attock",
      "Hasan Abdal", "Hasan Abdal Road",
      "Civil Lines Attock", "Model Town Attock",
      "Gondal Road", "Pindi Gheb Road",
      "Officers Colony Attock", "Railway Colony Attock",
      "City Center Attock", "Jand Road",
    ],
  },
  {
    name: "Okara",
    localities: [
      "Civil Lines Okara", "GT Road Okara",
      "Depalpur Road", "Cantt Okara",
      "Model Town Okara", "Satellite Town Okara",
      "Sahiwal Road Okara", "Renala Khurd Road",
      "Officers Colony Okara", "Railway Road Okara",
      "Peoples Colony Okara", "Muslim Town Okara",
      "Canal Colony Okara", "Bypass Okara",
      "Hospital Road Okara", "College Road Okara",
    ],
  },
  {
    name: "Kasur",
    localities: [
      "GT Road Kasur", "Civil Lines Kasur",
      "Pattoki", "Pattoki Road",
      "Chunian Road", "Chunian",
      "Model Town Kasur", "Cantt Kasur",
      "Ferozpur Road Kasur", "Lahore Road Kasur",
      "Depalpur Road Kasur", "Kot Radha Kishan",
      "Officers Colony Kasur", "Railway Colony Kasur",
      "Peoples Colony Kasur", "Canal Colony Kasur",
      "Bypass Kasur", "Old City Kasur",
    ],
  },
  {
    name: "Sheikhupura",
    localities: [
      "Civil Lines Sheikhupura", "GT Road Sheikhupura",
      "Faisalabad Road Sheikhupura", "Canal Colony Sheikhupura",
      "Model Town Sheikhupura", "Cantt Sheikhupura",
      "Lahore Road Sheikhupura", "Bypass Sheikhupura",
      "Satellite Town Sheikhupura", "Officers Colony Sheikhupura",
      "Peoples Colony Sheikhupura", "Mandiala Road",
      "Sharaqpur Road", "Muridke Road",
      "City Center Sheikhupura", "Railway Road Sheikhupura",
      "Industrial Estate Sheikhupura", "Hiran Minar Road",
    ],
  },
  {
    name: "Mianwali",
    localities: [
      "Cantt Mianwali", "Civil Lines Mianwali",
      "Isa Khel Road", "Main Bazaar Mianwali",
      "Model Town Mianwali", "Officers Colony Mianwali",
      "Sargodha Road Mianwali", "Bannu Road Mianwali",
      "Kalabagh Road", "Piplan Road",
      "Railway Road Mianwali", "Hospital Road Mianwali",
      "PAF Colony Mianwali", "University Road Mianwali",
      "Bypass Mianwali", "Chashma Road",
    ],
  },
  {
    name: "Bhakkar",
    localities: [
      "Civil Colony Bhakkar", "Hospital Road Bhakkar",
      "Darya Khan Road", "Main Bazaar Bhakkar",
      "Model Town Bhakkar", "Officers Colony Bhakkar",
      "Mankera Road", "Layyah Road Bhakkar",
      "DI Khan Road Bhakkar", "Bypass Bhakkar",
      "Railway Road Bhakkar", "City Center Bhakkar",
      "Kallur Kot Road", "Canal Colony Bhakkar",
    ],
  },
  {
    name: "Khushab",
    localities: [
      "Jauharabad", "Jauharabad City",
      "Noorpur Thal", "Noorpur Road",
      "Civil Lines Khushab", "Main Bazaar Khushab",
      "Model Town Khushab", "Officers Colony Khushab",
      "Sargodha Road Khushab", "Mianwali Road Khushab",
      "Railway Road Khushab", "Bypass Khushab",
      "Hospital Road Khushab", "City Center Khushab",
      "Quaidabad Khushab", "Sakesar Road",
    ],
  },
  {
    name: "Hafizabad",
    localities: [
      "Civil Lines Hafizabad", "Pindi Bhattian Road",
      "GT Road Hafizabad", "Sukheke",
      "Model Town Hafizabad", "Officers Colony Hafizabad",
      "Railway Road Hafizabad", "Bypass Hafizabad",
      "Jalalpur Bhattian Road", "Hospital Road Hafizabad",
      "City Center Hafizabad", "Vanike Tarar Road",
      "Canal Colony Hafizabad", "Peoples Colony Hafizabad",
    ],
  },
  {
    name: "Mandi Bahauddin",
    localities: [
      "Phalia", "Phalia City", "Phalia Road",
      "Malakwal", "Malakwal City",
      "Civil Lines MB Din", "GT Road MB Din",
      "Model Town MB Din", "Officers Colony MB Din",
      "Railway Road MB Din", "Hospital Road MB Din",
      "Bypass MB Din", "Sargodha Road MB Din",
      "Gujrat Road MB Din", "City Center MB Din",
      "Canal Colony MB Din", "Peoples Colony MB Din",
    ],
  },
  {
    name: "Narowal",
    localities: [
      "Zafarwal Road", "Shakargarh Road", "Shakargarh",
      "Civil Lines Narowal", "Main Bazaar Narowal",
      "Model Town Narowal", "Officers Colony Narowal",
      "Railway Road Narowal", "Bypass Narowal",
      "Hospital Road Narowal", "Sialkot Road Narowal",
      "City Center Narowal", "Canal Colony Narowal",
      "Peoples Colony Narowal", "GT Road Narowal",
    ],
  },
  {
    name: "Vehari",
    localities: [
      "Multan Road Vehari", "Burewala Road", "Burewala",
      "Civil Lines Vehari", "Model Town Vehari",
      "Officers Colony Vehari", "Railway Road Vehari",
      "Bypass Vehari", "Hospital Road Vehari",
      "City Center Vehari", "Canal Colony Vehari",
      "Peoples Colony Vehari", "Mailsi Road",
      "Luddan Road", "Hasilpur Road Vehari",
      "Satellite Town Vehari", "GT Road Vehari",
    ],
  },
  {
    name: "Lodhran",
    localities: [
      "Dunyapur Road", "Dunyapur",
      "Kehror Pacca Road", "Kehror Pacca",
      "Civil Lines Lodhran", "Main Bazaar Lodhran",
      "Model Town Lodhran", "Officers Colony Lodhran",
      "Railway Road Lodhran", "Bypass Lodhran",
      "Bahawalpur Road Lodhran", "Multan Road Lodhran",
      "Hospital Road Lodhran", "City Center Lodhran",
      "Canal Colony Lodhran", "Peoples Colony Lodhran",
    ],
  },
  {
    name: "Khanewal",
    localities: [
      "Civil Lines Khanewal", "Multan Road Khanewal",
      "Mian Channu", "Mian Channu City", "Mian Channu Road",
      "Kabirwala Road", "Kabirwala",
      "Model Town Khanewal", "Officers Colony Khanewal",
      "Railway Road Khanewal", "Bypass Khanewal",
      "Hospital Road Khanewal", "Jahanian Road",
      "City Center Khanewal", "Canal Colony Khanewal",
      "Peoples Colony Khanewal", "GT Road Khanewal",
    ],
  },
  {
    name: "Rajanpur",
    localities: [
      "Jampur", "Jampur City", "Jampur Road",
      "Fazilpur", "Fazilpur Road",
      "Civil Lines Rajanpur", "Main Bazaar Rajanpur",
      "Model Town Rajanpur", "Officers Colony Rajanpur",
      "DG Khan Road Rajanpur", "Bypass Rajanpur",
      "Hospital Road Rajanpur", "City Center Rajanpur",
      "Rojhan Road", "Indus Highway Rajanpur",
    ],
  },
  {
    name: "Muzaffargarh",
    localities: [
      "Civil Lines Muzaffargarh", "Alipur Road", "Alipur",
      "Kot Addu", "Kot Addu City", "Kot Addu Road",
      "Main Bazaar Muzaffargarh", "Model Town Muzaffargarh",
      "Officers Colony Muzaffargarh", "Railway Road Muzaffargarh",
      "Bypass Muzaffargarh", "Hospital Road Muzaffargarh",
      "DG Khan Road Muzaffargarh", "Multan Road Muzaffargarh",
      "City Center Muzaffargarh", "Canal Colony Muzaffargarh",
      "Peoples Colony Muzaffargarh", "Sanawan Road",
    ],
  },
  {
    name: "Layyah",
    localities: [
      "Chowk Azam", "Chowk Azam City",
      "Karor Lal Esan", "Karor Road",
      "Civil Lines Layyah", "Main Bazaar Layyah",
      "Model Town Layyah", "Officers Colony Layyah",
      "Railway Road Layyah", "Bypass Layyah",
      "Hospital Road Layyah", "City Center Layyah",
      "Bhakkar Road Layyah", "Muzaffargarh Road Layyah",
      "Canal Colony Layyah", "Peoples Colony Layyah",
    ],
  },
  {
    name: "Nowshera",
    localities: [
      "Cantt Nowshera", "Nowshera Cantt",
      "GT Road Nowshera", "Mardan Road Nowshera",
      "Risalpur Road", "Risalpur Cantt",
      "Pabbi Road", "Pabbi",
      "Civil Lines Nowshera", "Model Town Nowshera",
      "Officers Colony Nowshera", "Railway Road Nowshera",
      "Bypass Nowshera", "Akora Khattak Road",
      "Jehangira Road", "City Center Nowshera",
      "PAF Colony Nowshera", "Azakhel Road",
    ],
  },
  {
    name: "Mansehra",
    localities: [
      "Shinkiari Road", "Abbottabad Road Mansehra",
      "Balakot Road", "Naran Road",
      "Civil Lines Mansehra", "Model Town Mansehra",
      "Officers Colony Mansehra", "Main Bazaar Mansehra",
      "Bypass Mansehra", "Hospital Road Mansehra",
      "University Road Mansehra", "City Center Mansehra",
      "Oghi Road", "Battagram Road",
      "Railway Road Mansehra", "KKH Road Mansehra",
    ],
  },
  {
    name: "Mirpur Khas",
    localities: [
      "Station Road Mirpur Khas", "Civil Lines Mirpur Khas",
      "Umerkot Road", "Hyderabad Road Mirpur Khas",
      "Model Town Mirpur Khas", "Officers Colony Mirpur Khas",
      "Cantt Mirpur Khas", "Railway Road Mirpur Khas",
      "Hospital Road Mirpur Khas", "Bypass Mirpur Khas",
      "City Center Mirpur Khas", "Digri Road",
      "Peoples Colony Mirpur Khas", "Canal Colony Mirpur Khas",
    ],
  },
  {
    name: "Jacobabad",
    localities: [
      "Station Road Jacobabad", "Civil Lines Jacobabad",
      "Cantt Jacobabad", "Model Town Jacobabad",
      "Quetta Road Jacobabad", "Larkana Road Jacobabad",
      "Officers Colony Jacobabad", "Railway Colony Jacobabad",
      "Hospital Road Jacobabad", "City Center Jacobabad",
      "Bypass Jacobabad", "Garhi Khairo Road",
    ],
  },
  {
    name: "Shikarpur",
    localities: [
      "Main Bazaar Shikarpur", "Civil Lines Shikarpur",
      "Station Road Shikarpur", "Model Town Shikarpur",
      "Sukkur Road Shikarpur", "Larkana Road Shikarpur",
      "Officers Colony Shikarpur", "Hospital Road Shikarpur",
      "City Center Shikarpur", "Bypass Shikarpur",
      "Khanpur Road", "Lakhi Road",
    ],
  },
];

// ─── Helper: Get all city names ───────────────────────────────────────────────
export const ALL_CITY_NAMES: string[] = PAKISTAN_LOCATIONS.map((c) => c.name);

// ─── Helper: Get localities for a city ────────────────────────────────────────
export function getLocalitiesForCity(cityName: string): string[] {
  const city = PAKISTAN_LOCATIONS.find(
    (c) => c.name.toLowerCase() === cityName.toLowerCase()
  );
  return city?.localities ?? [];
}
